### ISSUE TITLE
May I use this dataset?

### ISSUE THREAD

**Issue by Daumel** [ggyggy666/DNS-Tunnel-Datasets#1]
Hello,

I am unsure of what I am allowed to do with this dataset, as there is no specified license. I would like to use your dataset as a foundation to extract features and save them in publicly available CSV files on GitHub.

Am I allowed to do this? I will, of course, reference your dataset and paper in my README.

**Comment by ggyggy666** [comment]
Hello,

Thank you for your interest in my dataset. I appreciate your intention to reference my work.

Regarding your question, I am happy for you to use my dataset to extract features and share them in publicly available CSV files on GitHub, as long as proper attribution is given. Please reference both my dataset and the related paper in your README, as you mentioned.

If you also use this dataset in your paper, please cite our dataset and paper.

Best regards！
